version: '3.9'

services:
  postgres:
    image: postgres:15.2
    container_name: fintech_postgres
    environment:
      POSTGRES_USER: fintech
      POSTGRES_PASSWORD: fintechuser
      POSTGRES_DB: fintechdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v2.21.0
    container_name: fintech_hasura
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://fintech:fintechuser@postgres:5432/fintechdatabase
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"

volumes:
  postgres_data:
